/**
  * @file bsp.c 
  * @brief  Board Support Package source file
  * @author Leon Lee (leonlee.scut@outlook.com)
  * @version 0.1
  * @date 2025/08/07
  * 
  * @copyright Copyright (c) 2025 South China University of Technology.
  * All rights reserved.
  * 
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  * 
  * @par History:
  * 	Date		Version		Author			Description
  * 	2025/08/07	0.1			Leon Lee		Preliminary version.
  */
 
/**
  * @Note 
  *     In project which is generated by STM32CubeMX, hardware functions are 
  *     defined in STM32CubeMX, and initialized in main.c. So the BSP modules 
  *     initialization functions do not include any hardware initialization functions.
  *
  *     In this project:
  *       TIMER1 is used as PWM timer, generate 25kHz PWM signal on TIM_CHANNEL_1. 
  *       TIMER3 is used as CAP timer, capture frequency on TIM_CHANNEL_3 and TIM_CHANNEL_4.
  *       TIMER15 is used as ADC trigger timer, trigger ADC conversion every 125ms 
  *             and synchronously by TIMER3 period update event. 
  *       ADC1 is used as ADC, with DMA enabled, and 8 channels are configured.
  *             ADC1 sample rate is 1 Hz, 8x oversampling triggered by TIMER15.
  * 
  */


#include "bsp.h"


/**
 * @brief Initializes the Board Support Package (BSP).
 *
 * Initializes the PWM, CAP, and ADC modules.
 * This function should be called first before any other BSP functions.
 */
void bsp_init(void)
{
    bsp_pwm_init(PWM_TIMER_HANDLE, PWM_OC_CHANNEL); // Initialize PWM
    bsp_cap_init(CAP_CH1, CAP_TIMER_HANDLE, CAP_CH1_TIM_CHANNEL);    // Initialize CAP CH1
    bsp_cap_init(CAP_CH2, CAP_TIMER_HANDLE, CAP_CH2_TIM_CHANNEL);    // Initialize CAP CH2
    bsp_adc_init(ADC_HANDLE, ADC_DMA_HANDLE, EXT_ADC_TRIG_TIMER_HANDLE); // Initialize ADC

}

  
/************* (C) COPYRIGHT South China Univ. of Tech. ****** END OF FILE ****/
